name: Azure Static Web Apps CI/CD

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - webapp/**
      - .github/workflows/azure-static-web-apps-icy-sand-0913d0b03.yml
    branches:
      - main

jobs:
  build:
    #if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - name: Run Tests
        run: |
          cd webapp
          npm install
          npm test
          
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_SAND_0913D0B03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/webapp" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional

  deploy:
    #if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    needs: build
    name: Deploy
    steps:
      - name: Deploy
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_SAND_0913D0B03 }}
          action: "close"
