name: Build and deploy JAR app to Azure Web App - vfarecruitmentgateway

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - services/gateway/**
      - .github/workflows/main_vfarecruitmentgateway.yml
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          cd services/gateway
          echo "spring.datasource.url= ${{ secrets.DB_URL }}" >> ./src/main/resources/application.properties
          echo "spring.datasource.username= ${{ secrets.DB_USERNAME }}" >> ./src/main/resources/application.properties
          echo "spring.datasource.password= ${{ secrets.DB_PASSWORD }}" >> ./src/main/resources/application.properties
          echo "cors.frontend.url= https://icy-sand-0913d0b03.2.azurestaticapps.net" >> ./src/main/resources/application.properties
          cat ./src/main/resources/application.properties
          mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/services/gateway/target/'

  deploy:
    #if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/services/gateway/target/'

      - name: Files
        run: |
          ls services/gateway/target

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'vfarecruitmentgateway'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6DC9624A199A46C8B4FDDED3DD394A8C }}
          package: 'services/gateway/target/*.jar'
